"""dropped emailtype

Revision ID: 02564a85a6c0
Revises: 1a8d64d83725
Create Date: 2020-10-11 21:33:14.755065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02564a85a6c0'
down_revision = '1a8d64d83725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emailtype_id', table_name='emailtype')
    op.drop_table('emailtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailtype',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='emailtype_pkey')
    )
    op.create_index('ix_emailtype_id', 'emailtype', ['id'], unique=False)
    # ### end Alembic commands ###
