"""

Revision ID: 1a8d64d83725
Revises: ae98354ff84f
Create Date: 2020-10-11 21:32:50.720518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8d64d83725'
down_revision = 'ae98354ff84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_emailtype_id_fkey', 'email', type_='foreignkey')
    op.drop_column('email', 'emailtype_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('emailtype_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('email_emailtype_id_fkey', 'email', 'emailtype', ['emailtype_id'], ['id'])
    # ### end Alembic commands ###
