"""added category enum

Revision ID: 8dc212a41ff7
Revises: 02564a85a6c0
Create Date: 2020-10-11 21:33:51.878274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8dc212a41ff7'
down_revision = '02564a85a6c0'
branch_labels = None
depends_on = None


def upgrade():
    categoryenum = postgresql.ENUM('general', 'newaccount', 'paswordreset', name='categoryenum')
    categoryenum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('general', 'newaccount', 'paswordreset', name='categoryenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'category',
               existing_type=sa.Enum('general', 'newaccount', 'paswordreset', name='categoryenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
