"""

Revision ID: ae98354ff84f
Revises: 
Create Date: 2020-10-11 21:32:36.133151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae98354ff84f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailtype_id'), 'emailtype', ['id'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('cc', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('date_sent', sa.Boolean(), nullable=True),
    sa.Column('emailtype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emailtype_id'], ['emailtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=False)
    op.create_index(op.f('ix_email_recipient'), 'email', ['recipient'], unique=False)
    op.create_index(op.f('ix_email_sender'), 'email', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_sender'), table_name='email')
    op.drop_index(op.f('ix_email_recipient'), table_name='email')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_emailtype_id'), table_name='emailtype')
    op.drop_table('emailtype')
    # ### end Alembic commands ###
