version: '3.5'

services:
    users:
        container_name: users
        restart: unless-stopped
        build:
            context: ./backend/users
        volumes:
            - ./backend/users:/app
        expose:
            - "8050"
        ports:
            - 8050:8000
        depends_on:
            - users_db
        networks:
            - smartnet1
        command: bash -c "cd src && ./runserver.sh"

    users_db:
        container_name: users_db
        image: postgres:12
        restart: unless-stopped
        environment:
            - POSTGRES_DB=users_db
            - POSTGRES_USER=users_admin
            - POSTGRES_PASSWORD=Access123
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres/users/init/:/docker-entrypoint-initdb.d/
            - users-data:/var/lib/postgresql/data
        ports:
            - 5450:5432
        networks:
            - smartnet1

    messages:
        container_name: messages
        restart: unless-stopped
        build:
            context: ./backend/messages
        volumes:
            - ./backend/messages:/app
        expose:
            - "8051"
        ports:
            - 8051:8000
        depends_on:
            - messages_db
        networks:
            - smartnet1
        command: bash -c "cd src && ./runserver.sh"

    messages_db:
        container_name: messages_db
        image: postgres:12
        restart: unless-stopped
        environment:
            - POSTGRES_DB=messages_db
            - POSTGRES_USER=messages_admin
            - POSTGRES_PASSWORD=Access123
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres/messages/init/:/docker-entrypoint-initdb.d/
            - messages-data:/var/lib/postgresql/data
        ports:
            - 5451:5432
        networks:
            - smartnet1

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - smartnet1
        restart: unless-stopped
        depends_on:
            - users_db
            - messages_db
    

    # frontend:
    #     container_name: felicity.fe
    #     restart: unless-stopped
    #     build:
    #         context: ./frontend
    #     volumes:
    #         - ./frontend:/app
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - backend
    #     networks:
    #         - smartnet1
    #     command: bash -c "cd vite && yarn dev"

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./services/nginx:/etc/nginx/conf.d
        depends_on:
            - users
            - messages
        networks:
            - smartnet1

volumes:
    users-data:
    messages-data:
    pgadmin:

networks:
    smartnet1:
        driver: bridge